# Generated by Django 5.1.1 on 2024-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
